name: Trigger auto deployment for aws-uks-poc-capp-snd01

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/aws-uks-poc-capp-snd01-AutoDeployTrigger-b8b46114-fea1-461d-a7e9-4647ff2304e4.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
            enable-AzPSSession: true
      
      - name: 'Get resource group with PowerShell action'
        uses: azure/powershell@v1
        with:
           inlineScript: |
             Get-AzResourceGroup
           azPSVersion: "latest"

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.AWSUKSPOCCAPPSND01_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AWSUKSPOCCAPPSND01_REGISTRY_PASSWORD }}
          containerAppName: aws-uks-poc-capp-snd01
          resourceGroup: ashleyTest
          imageToBuild: containerRegistryAshleyTest/aws-uks-poc-capp-snd01:${{ github.sha }}
          

     

